//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMovieTicketSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seattbl
    {
        public int SeatId { get; set; }
        public string Ticket { get; set; }
    }
}
