//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMovieTicketSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_Theater
    {
        public int TheaterId { get; set; }
        [Required(ErrorMessage = "Theater name is required")]
        public string TheaterName { get; set; }
        [Required(ErrorMessage = "Theater city is required")]
        public string TheaterCity { get; set; }
        [Required(ErrorMessage = "Movie name is required")]
        public string MovieNames { get; set; }
        [Required(ErrorMessage = "Screen type is required")]
        public string ListOfScreens { get; set; }
        [Required(ErrorMessage = "Manager name is required")]
        public string ManagerName { get; set; }
    }  
}
