//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcFirstDBApproach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StuId { get; set; }
        public string StuName { get; set; }
        public Nullable<int> Age { get; set; }
    }
}
